version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SMTP_USER=${SMTP_USER}
      - RECIPIENT=${RECIPIENT}
      - ETH_CONTRACT_ADDRESS=${ETH_CONTRACT_ADDRESS}
      - BTC_CONTRACT_ADDRESS=${BTC_CONTRACT_ADDRESS}
      - POLY_CONTRACT_ADDRESS=${POLY_CONTRACT_ADDRESS}
      - CHAIN_MORALIS_ETH=${CHAIN_MORALIS_ETH}
      - CHAIN_MORALIS_POLYGON=${CHAIN_MORALIS_POLYGON}
    depends_on:
      - postgres
    user: "node"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:prod"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: